AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-source-bucket'
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt S3BucketSourceRole.Arn
        Rules:
          - Destination:
              Bucket: !GetAtt TargetBucket.Arn
            Status: Enabled

  TargetBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-target-bucket'
      VersioningConfiguration:
        Status: Enabled

  S3BucketSourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-bucket-source-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "s3-replication-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetReplicationConfiguration
                Resource:
                  - !Sub "arn:aws:s3:::${AWS::StackName}-source-bucket"
              - Effect: Allow
                Action:
                 - s3:GetObjectVersionForReplication
                 - s3:GetObjectVersionAcl
                 - s3:GetObjectVersionTagging
                Resource:
                  - !Sub "arn:aws:s3:::${AWS::StackName}-source-bucket/*"
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource:
                  - !Sub "arn:aws:s3:::${AWS::StackName}-target-bucket/*"
