name: ci

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Validate CloudFormation template
      run: aws cloudformation validate-template --template-body file://template.yml
